/*
 * Onfido API
 *
 * The Onfido API is used to submit check requests.
 *
 * API version: 3.4.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Error object. Only set when the Workflow Run status is 'error'.
type InlineResponse2012Error struct {
	// The type of error.
	Type_ string `json:"type,omitempty"`
	// A textual description of the error.
	Message string `json:"message,omitempty"`
}
