/*
 * Onfido API
 *
 * The Onfido API is used to submit check requests.
 *
 * API version: 3.4.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ApplicantsAddress struct {
	// The flat number of this address
	FlatNumber string `json:"flat_number,omitempty"`
	// The building number of this address
	BuildingNumber string `json:"building_number,omitempty"`
	// The building name of this address
	BuildingName string `json:"building_name,omitempty"`
	// The street of the applicant’s address
	Street string `json:"street,omitempty"`
	// The sub-street of the applicant’s address
	SubStreet string `json:"sub_street,omitempty"`
	// The town of the applicant’s address
	Town string `json:"town,omitempty"`
	// The postcode or ZIP of the applicant’s address
	Postcode string `json:"postcode,omitempty"`
	// The 3 character ISO country code of this address. For example, GBR is the country code for the United Kingdom
	Country string `json:"country,omitempty"`
	// The address state. US states must use the USPS abbreviation (see also ISO 3166-2:US), for example AK, CA, or TX.
	State string `json:"state,omitempty"`
	// Line 1 of the applicant's address
	Line1 string `json:"line1,omitempty"`
	// Line 2 of the applicant's address
	Line2 string `json:"line2,omitempty"`
	// Line 3 of the applicant's address
	Line3 string `json:"line3,omitempty"`
}
