/*
 * Onfido API
 *
 * The Onfido API is used to submit check requests.
 *
 * API version: 3.4.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// SDK metadata of the device used in the Authentication process.
type InlineResponse20014SdkMetadata struct {
	System *InlineResponse20014SdkMetadataSystem `json:"system,omitempty"`
}
