/*
 * Onfido API
 *
 * The Onfido API is used to submit check requests.
 *
 * API version: 3.4.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type InlineResponse2003 struct {
	LiveVideos []Paths1liveVideos17BliveVideoId7Dgetresponses200contentapplication1jsonschema `json:"live_videos,omitempty"`
}
