/*
 * Onfido API
 *
 * The Onfido API is used to submit check requests.
 *
 * API version: 3.4.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type InlineResponse20011 struct {
	Addresses []Paths1applicantspostrequestBodycontentapplication1jsonschemapropertiesaddress `json:"addresses,omitempty"`
}
