/*
 * Onfido API
 *
 * The Onfido API is used to submit check requests.
 *
 * API version: 3.4.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"os"
)

type LivePhotosBody struct {
	ApplicantId string `json:"applicant_id"`
	// The file to be uploaded.
	File **os.File `json:"file"`
	// Validates that the live photo contains exactly one face.
	AdvancedValidation bool `json:"advanced_validation,omitempty"`
}
