/*
 * Onfido API
 *
 * The Onfido API is used to submit check requests.
 *
 * API version: 3.4.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

type InlineResponse2008Tasks struct {
	// The identifier for the Task.
	Id string `json:"id,omitempty"`
	// The identifier for the Task Definition.
	TaskDefId string `json:"task_def_id,omitempty"`
	// The date and time when the Task was created.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// The date and time when the Task was last updated.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
}
