/*
 * Onfido API
 *
 * The Onfido API is used to submit check requests.
 *
 * API version: 3.4.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

type ApplicantsBody struct {
	// The unique identifier for the applicant. Read-only.
	Id string `json:"id,omitempty"`
	// The date and time when this applicant was created. Read-only.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// The date and time when this applicant is scheduled to be deleted. Read-only.
	DeleteAt time.Time `json:"delete_at,omitempty"`
	// The uri of this resource. Read-only.
	Href string `json:"href,omitempty"`
	// Read-only.
	Sandbox bool `json:"sandbox,omitempty"`
	// The applicant’s first name
	FirstName string `json:"first_name,omitempty"`
	// The applicant’s surname
	LastName string `json:"last_name,omitempty"`
	// The applicant’s email address. Required if doing a US check, or a UK check for which `applicant_provides_data` is `true`.
	Email string `json:"email,omitempty"`
	// The applicant’s date of birth
	Dob string `json:"dob,omitempty"`
	Address *ApplicantsAddress `json:"address,omitempty"`
	IdNumbers []ApplicantsIdNumbers `json:"id_numbers,omitempty"`
	// The applicant’s phone number
	PhoneNumber string `json:"phone_number,omitempty"`
	Consents []ModelMap `json:"consents,omitempty"`
	Location *ApplicantsLocation `json:"location,omitempty"`
}
