/*
 * Onfido API
 *
 * The Onfido API is used to submit check requests.
 *
 * API version: 3.4.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type InlineResponse20014SdkMetadataSystem struct {
	Product string `json:"product,omitempty"`
	Model string `json:"model,omitempty"`
	Manufacturer string `json:"manufacturer,omitempty"`
	Hardware string `json:"hardware,omitempty"`
	Fingerprint string `json:"fingerprint,omitempty"`
	Brand string `json:"brand,omitempty"`
}
