/*
 * Onfido API
 *
 * The Onfido API is used to submit check requests.
 *
 * API version: 3.4.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ApplicantsLocation struct {
	// The applicant's ip address.
	IpAddress string `json:"ip_address,omitempty"`
	// The applicant's country of residence.
	CountryOfResidence string `json:"country_of_residence,omitempty"`
}
