/*
 * Onfido API
 *
 * The Onfido API is used to submit check requests.
 *
 * API version: 3.4.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ErrorProperties struct {
	Type_ string `json:"type,omitempty"`
	Message string `json:"message,omitempty"`
	Fields ModelMap `json:"fields,omitempty"`
}
