/*
 * Onfido API
 *
 * The Onfido API is used to submit check requests.
 *
 * API version: 3.4.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type WorkflowRunsBody struct {
	// The unique identifier for the Workflow.
	WorkflowId string `json:"workflow_id"`
	// The unique identifier for the Applicant.
	ApplicantId string `json:"applicant_id"`
	// Optional object with custom input data to be used in the Workflow Run.
	CustomData *interface{} `json:"custom_data,omitempty"`
	// Optional object for the configuration of the Workflow Run link.
	Link *interface{} `json:"link,omitempty"`
}
