/*
 * Onfido API
 *
 * The Onfido API is used to submit check requests.
 *
 * API version: 3.4.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"os"
)

// You must pass one of the parameters to create a trusted face. The parameters are mutually exclusive.
type ApplicantIdFaceBody struct {
	// The file to be uploaded.
	File **os.File `json:"file,omitempty"`
	// The unique identifier of the live photo.
	LivePhotoId string `json:"live_photo_id,omitempty"`
	// The unique identifier of the live video.
	LiveVideoId string `json:"live_video_id,omitempty"`
}
