/*
 * Onfido API
 *
 * The Onfido API is used to submit check requests.
 *
 * API version: 3.4.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type WebhooksBody struct {
	// The unique identifier of the webhook. Read-only.
	Id string `json:"id,omitempty"`
	// Webhook secret token used to sign the webhook's payload. Read-only.
	Token string `json:"token,omitempty"`
	// The API endpoint to retrieve the webhook. Read-only.
	Href string `json:"href,omitempty"`
	// The url that will listen to notifications (must be https).
	Url string `json:"url"`
	// Determine if the webhook is active.
	Enabled bool `json:"enabled,omitempty"`
	// The environments from which the webhook will receive events. Allowed values are “sandbox” and “live”. If the environments parameter is omitted the webhook will receive events from both environments. 
	Environments []string `json:"environments,omitempty"`
	// The events that will be published to the webhook. The supported events are: `report.completed`, `report.withdrawn`, `check.completed`, `check.started`, `check.form_opened`, `check.form_completed`. If the events parameter is omitted all the events will be subscribed. 
	Events []string `json:"events,omitempty"`
}
