/*
 * Onfido API
 *
 * The Onfido API is used to submit check requests.
 *
 * API version: 3.4.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type InlineResponse2006 struct {
	Reports []Paths1reports17BreportId7Dgetresponses200contentapplication1jsonschema `json:"reports,omitempty"`
}
