/*
 * Onfido API
 *
 * The Onfido API is used to submit check requests.
 *
 * API version: 3.4.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

type InlineResponse2004 struct {
	// The unique identifier for the video.
	Id string `json:"id,omitempty"`
	// The date and time at which the video was uploaded.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// The uri of this resource.
	Href string `json:"href,omitempty"`
	// The uri that can be used to download the video.
	DownloadHref string `json:"download_href,omitempty"`
	// The name of the uploaded file.
	FileName string `json:"file_name,omitempty"`
	// The size of the file in bytes.
	FileSize int32 `json:"file_size,omitempty"`
	// The file type of the uploaded file.
	FileType string `json:"file_type,omitempty"`
}
