/*
 * Onfido API
 *
 * The Onfido API is used to submit check requests.
 *
 * API version: 3.4.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

type ChecksBody struct {
	// The unique identifier for the check. Read-only.
	Id string `json:"id,omitempty"`
	// The date and time when this check was created. Read-only.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// The uri of this resource. Read-only.
	Href string `json:"href,omitempty"`
	// The current state of the check in the checking process. Read-only.
	Status string `json:"status,omitempty"`
	// The overall result of the check, based on the results of the constituent reports. Read-only.
	Result string `json:"result,omitempty"`
	// A link to a PDF output of the check results. Append `.pdf` to get the pdf file. Read-only.
	DownloadUri string `json:"download_uri,omitempty"`
	// A link to the applicant form, if `applicant_provides_data` is `true`. Read-only.
	FormUri string `json:"form_uri,omitempty"`
	// For checks where `applicant_provides_data` is `true`, redirect to this URI when the applicant has submitted their data. Read-only.
	RedirectUri string `json:"redirect_uri,omitempty"`
	// A link to the corresponding results page on the Onfido dashboard.
	ResultsUri string `json:"results_uri,omitempty"`
	// An array of report names (strings).
	ReportNames []string `json:"report_names,omitempty"`
	// The ID of the applicant to do the check on.
	ApplicantId string `json:"applicant_id,omitempty"`
	// Indicates whether the privacy notices and terms of service have been read and, where specific laws require, that consent has been given for Onfido.
	PrivacyNoticesReadConsentGiven bool `json:"privacy_notices_read_consent_given,omitempty"`
	// Array of tags being assigned to this check.
	Tags []string `json:"tags,omitempty"`
	// Send an applicant form to applicant to complete to proceed with check. Defaults to false. 
	ApplicantProvidesData bool `json:"applicant_provides_data,omitempty"`
	// For checks where `applicant_provides_data` is `true`, applicant form will not be automatically sent if `suppress_form_emails` is set to `true`. You can manually send the form at any time after the check has been created, using the link found in the form_uri attribute of the check object. Write-only. Defaults to false. 
	SuppressFormEmails bool `json:"suppress_form_emails,omitempty"`
	// Defaults to `true`. Write-only. If set to `false`, you will only receive a response when all reports in your check have completed. 
	Asynchronous bool `json:"asynchronous,omitempty"`
	// Optional. An array of strings describing which webhooks to trigger for this check. By default, all webhooks registered in the account will be triggered and this value will be null in the responses.
	WebhookIds []string `json:"webhook_ids,omitempty"`
	// An array of report ids.
	ReportIds []string `json:"report_ids,omitempty"`
	// Optional. Array of strings describing which document to process in checks containing a Document report or a Facial Similarity report, or both. By default, the most recently uploaded document is used. `document_ids` is only usable with Document and Facial Similarity reports.
	DocumentIds []string `json:"document_ids,omitempty"`
	// Returns a pre-determined consider sub-result in sandbox for the specific reports in the consider array.
	Consider []string `json:"consider,omitempty"`
	// Triggers a pre-determined sub-result response for sandbox Document reports.
	SubResult string `json:"sub_result,omitempty"`
}
