/*
 * Onfido API
 *
 * The Onfido API is used to submit check requests.
 *
 * API version: 3.4.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type InlineResponse20013 struct {
	// The specific cryptographic algorithm used with the key.
	Alg string `json:"alg,omitempty"`
	// The family of cryptographic algorithms used with the key.
	Kty string `json:"kty,omitempty"`
	// How the key was meant to be used.
	Use string `json:"use,omitempty"`
	// The modulus for the RSA public key.
	N string `json:"n,omitempty"`
	// The exponent for the RSA public key.
	E string `json:"e,omitempty"`
	// The unique identifier for the key.
	Kid string `json:"kid,omitempty"`
}
