/*
 * Onfido API
 *
 * The Onfido API is used to submit check requests.
 *
 * API version: 3.4.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
	"os"
)

type InlineResponse20014Attempts struct {
	// The UUID of the Authentication attempt.
	Id string `json:"id,omitempty"`
	// The UUID of the applicant that made the attempt.
	ApplicantId string `json:"applicant_id,omitempty"`
	// The date and time at which the attempt was made.
	Timestamp time.Time `json:"timestamp,omitempty"`
	// The result of the Authentication attempt.
	Success bool `json:"success,omitempty"`
	// The reason why an Authentication attempt failed.
	Error_ string `json:"error,omitempty"`
	// SDK type used in the Authentication attempt.
	SdkSource string `json:"sdk_source,omitempty"`
	// SDK version used in the Authentication attempt.
	SdkVersion string `json:"sdk_version,omitempty"`
	SdkMetadata *InlineResponse20014SdkMetadata `json:"sdk_metadata,omitempty"`
	// The href to download the audit image used for the attempt.
	ImageHref **os.File `json:"image_href,omitempty"`
}
