/*
 * Onfido API
 *
 * The Onfido API is used to submit check requests.
 *
 * API version: 3.4.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type InlineResponse2002 struct {
	LivePhotos []Paths1livePhotospostresponses201contentapplication1jsonschema `json:"live_photos,omitempty"`
}
