/*
 * Onfido API
 *
 * The Onfido API is used to submit check requests.
 *
 * API version: 3.4.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type SdkTokenBody struct {
	// The unique identifier of the applicant
	ApplicantId string `json:"applicant_id,omitempty"`
	// The referrer URL pattern
	Referrer string `json:"referrer,omitempty"`
	// The application ID (iOS or Android)
	ApplicationId string `json:"application_id,omitempty"`
	// Enterprise Feature - The URL to be used for the cross device flow of the Web SDK
	CrossDeviceUrl string `json:"cross_device_url,omitempty"`
	// The generated SDK token
	Token string `json:"token,omitempty"`
}
