/*
 * Onfido API
 *
 * The Onfido API is used to submit check requests.
 *
 * API version: 3.4.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

// Object for the configuration of the Workflow Run link.
type InlineResponse2012Link struct {
	// Link to access the Workflow Run without the need to integrate with Onfido's SDKs.
	Url string `json:"url,omitempty"`
	// When the interactive section of the Workflow Run has completed successfully, the user will be redirected to this URL instead of seeing the default Onfido 'thank you' page.
	CompletedRedirectUrl string `json:"completed_redirect_url,omitempty"`
	// When the link has expired, the user will be immediately redirected to this URL instead of seeing the default Onfido error message.
	ExpiredRedirectUrl string `json:"expired_redirect_url,omitempty"`
	// Date and time when the link will expire.
	ExpiresAt time.Time `json:"expires_at,omitempty"`
	// The code for the language when the workflow run is acessed using the link.
	Language string `json:"language,omitempty"`
}
