### Send POST request with json body
POST https://27c75juvcgxrqmvb22wdbnrvra0jwnjd.lambda-url.us-east-1.on.aws/
Content-Type: application/json

{
  "amount": 999,
  "line_items": ["food", "shelter"]
}
